import Foundation

enum MaskObjectLabelCatalog {
    typealias Entry = (label: String, aliases: [String])

    static let entries: [Entry] = [
        ("wall", ["mur", "壁", "墙", "牆", "tường"]),
        ("building", ["bâtiment", "建物", "建筑物", "建築物", "tòa nhà"]),
        ("sky", ["ciel", "空", "天空", "bầu trời"]),
        ("floor", ["sol", "床面", "フロア", "地板", "sàn nhà"]),
        ("tree", ["arbre", "木", "树", "樹", "cây"]),
        ("ceiling", ["plafond", "天井", "天花板", "trần nhà"]),
        ("road", ["route", "道路", "路", "con đường"]),
        ("bed", ["lit", "ベッド", "床", "床铺", "床鋪", "giường", "cái giường"]),
        ("windowpane", ["vitre", "窓ガラス", "窗玻璃", "kính cửa sổ"]),
        ("grass", ["herbe", "草", "cỏ"]),
        ("cabinet", ["placard", "キャビネット", "橱柜", "櫥櫃", "tủ"]),
        ("sidewalk", ["trottoir", "歩道", "人行道", "vỉa hè"]),
        ("person", ["personne", "人物", "人", "người"]),
        ("earth", ["terre", "大地", "土壤", "đất"]),
        ("door", ["porte", "ドア", "门", "門", "cửa"]),
        ("table", ["table", "テーブル", "桌子", "bàn"]),
        ("mountain", ["montagne", "山", "núi"]),
        ("plant", ["plante", "植物", "cây cảnh"]),
        ("curtain", ["rideau", "カーテン", "窗帘", "窗簾", "rèm cửa"]),
        ("chair", ["chaise", "椅子", "ghế"]),
        ("car", ["voiture", "車", "汽车", "汽車", "ô tô", "xe hơi"]),
        ("water", ["eau", "水", "nước"]),
        ("painting", ["tableau", "絵画", "画作", "畫作", "tranh"]),
        ("sofa", ["canapé", "couch", "ソファ", "沙发", "沙發", "ghế sofa"]),
        ("shelf", ["étagère", "棚", "架子", "kệ"]),
        ("house", ["maison", "家", "房子", "ngôi nhà"]),
        ("sea", ["mer", "海", "biển"]),
        ("mirror", ["miroir", "鏡", "镜子", "鏡子", "gương"]),
        ("rug", ["tapis", "ラグ", "地毯", "thảm"]),
        ("field", ["champ", "畑", "田野", "cánh đồng"]),
        ("armchair", ["fauteuil", "アームチェア", "扶手椅", "ghế bành"]),
        ("seat", ["siège", "座席", "座位", "chỗ ngồi"]),
        ("fence", ["clôture", "フェンス", "栅栏", "柵欄", "hàng rào"]),
        ("desk", ["bureau", "机", "书桌", "書桌", "bàn làm việc"]),
        ("rock", ["rocher", "岩", "岩石", "tảng đá"]),
        ("wardrobe", ["armoire", "ワードローブ", "衣柜", "衣櫃", "tủ quần áo"]),
        ("lamp", ["lampe", "ランプ", "灯", "燈", "đèn bàn"]),
        ("bathtub", ["baignoire", "浴槽", "浴缸", "bồn tắm"]),
        ("railing", ["garde-corps", "手すり", "栏杆", "欄杆", "lan can"]),
        ("cushion", ["coussin", "クッション", "靠垫", "靠墊", "đệm tựa"]),
        ("base", ["socle", "台座", "底座", "đế"]),
        ("box", ["boîte", "箱", "盒子", "hộp"]),
        ("column", ["colonne", "柱", "柱子", "cột"]),
        ("signboard", ["enseigne", "看板", "招牌", "bảng hiệu"]),
        ("chest of drawers", ["commode", "たんす", "抽屉柜", "抽屜櫃", "tủ ngăn kéo"]),
        ("counter", ["comptoir", "カウンター", "柜台", "櫃檯", "quầy"]),
        ("sand", ["sable", "砂", "沙子", "cát"]),
        ("sink", ["évier", "流し台", "水槽", "bồn rửa"]),
        ("skyscraper", ["gratte-ciel", "超高層ビル", "摩天大楼", "摩天大樓", "nhà chọc trời"]),
        ("fireplace", ["cheminée", "暖炉", "壁炉", "壁爐", "lò sưởi"]),
        ("refrigerator", ["réfrigérateur", "冷蔵庫", "冰箱", "tủ lạnh"]),
        ("grandstand", ["tribune", "観客席", "看台", "khán đài"]),
        ("path", ["chemin", "小道", "小径", "小徑", "lối đi"]),
        ("stairs", ["escaliers", "階段", "楼梯", "樓梯", "cầu thang"]),
        ("runway", ["piste", "滑走路", "跑道", "đường băng"]),
        ("case", ["étui", "ケース", "箱体", "箱體", "vỏ hộp"]),
        ("pool table", ["table de billard", "ビリヤード台", "台球桌", "bàn bi-a"]),
        ("pillow", ["oreiller", "枕", "枕头", "枕頭", "gối"]),
        ("screen door", ["porte moustiquaire", "網戸", "纱门", "紗門", "cửa lưới"]),
        ("stairway", ["cage d'escalier", "階段通路", "楼梯通道", "樓梯通道", "lối cầu thang"]),
        ("river", ["rivière", "川", "河流", "sông"]),
        ("bridge", ["pont", "橋", "桥", "cầu"]),
        ("bookcase", ["bibliothèque", "本棚", "书柜", "書櫃", "tủ sách"]),
        ("blind", ["store", "ブラインド", "百叶窗", "百葉窗", "mành che"]),
        ("coffee table", ["table basse", "コーヒーテーブル", "茶几", "bàn trà"]),
        ("toilet", ["toilettes", "トイレ", "马桶", "馬桶", "bồn cầu"]),
        ("flower", ["fleur", "花", "hoa"]),
        ("book", ["livre", "本", "书", "書", "sách"]),
        ("hill", ["colline", "丘", "小山", "đồi"]),
        ("bench", ["banc", "ベンチ", "长椅", "長椅", "ghế dài"]),
        ("countertop", ["plan de travail", "カウンタートップ", "台面", "mặt bàn bếp"]),
        ("stove", ["cuisinière", "コンロ", "炉灶", "爐灶", "bếp"]),
        ("palm", ["palmier", "ヤシ", "棕榈树", "棕櫚樹", "cây cọ"]),
        ("kitchen island", ["îlot de cuisine", "キッチンアイランド", "厨房岛台", "廚房島台", "đảo bếp"]),
        ("computer", ["ordinateur", "コンピューター", "电脑", "電腦", "máy tính"]),
        ("swivel chair", ["chaise pivotante", "回転椅子", "转椅", "轉椅", "ghế xoay"]),
        ("boat", ["bateau", "ボート", "船", "thuyền"]),
        ("bar", ["bar", "バー", "吧台", "quầy bar"]),
        ("arcade machine", ["borne d'arcade", "アーケードゲーム機", "街机", "街機", "máy game thùng"]),
        ("hovel", ["taudis", "小屋", "棚屋", "túp lều"]),
        ("bus", ["bus", "バス", "公交车", "公車", "xe buýt"]),
        ("towel", ["serviette", "タオル", "毛巾", "khăn"]),
        ("light", ["éclairage", "照明", "灯光", "燈光", "đèn"]),
        ("truck", ["camion", "トラック", "卡车", "卡車", "xe tải"]),
        ("tower", ["tour", "塔", "tháp"]),
        ("chandelier", ["lustre", "シャンデリア", "吊灯", "吊燈", "đèn chùm"]),
        ("awning", ["auvent", "オーニング", "遮阳篷", "遮陽篷", "mái hiên"]),
        ("streetlight", ["lampadaire", "街灯", "路灯", "路燈", "đèn đường"]),
        ("booth", ["cabine", "ブース", "亭子", "gian hàng"]),
        ("television receiver", ["télévision", "tv", "テレビ", "电视", "電視", "tivi"]),
        ("airplane", ["avion", "飛行機", "飞机", "飛機", "máy bay"]),
        ("dirt track", ["piste en terre", "未舗装路", "土路", "đường đất"]),
        ("apparel", ["vêtement", "衣服", "服装", "服裝", "quần áo"]),
        ("pole", ["poteau", "ポール", "杆", "cột trụ"]),
        ("land", ["terrain", "土地", "陆地", "陸地", "mặt đất"]),
        ("bannister", ["rampe d'escalier", "階段手すり", "楼梯扶手", "樓梯扶手", "tay vịn cầu thang"]),
        ("escalator", ["escalier mécanique", "エスカレーター", "自动扶梯", "自動扶梯", "thang cuốn"]),
        ("ottoman", ["pouf", "オットマン", "脚凳", "ghế đôn"]),
        ("bottle", ["bouteille", "ボトル", "瓶子", "chai"]),
        ("buffet", ["buffet", "サイドボード", "餐边柜", "餐邊櫃", "tủ buffet"]),
        ("poster", ["affiche", "ポスター", "海报", "海報", "áp phích"]),
        ("stage", ["scène", "舞台", "sân khấu"]),
        ("van", ["fourgonnette", "バン", "面包车", "廂型車", "xe van"]),
        ("ship", ["navire", "船舶", "轮船", "輪船", "tàu thủy"]),
        ("fountain", ["fontaine", "噴水", "喷泉", "噴泉", "đài phun nước"]),
        ("conveyer belt", ["convoyeur", "コンベヤーベルト", "传送带", "傳送帶", "băng chuyền"]),
        ("canopy", ["dais", "天蓋", "顶篷", "頂篷", "mái che"]),
        ("washer", ["machine à laver", "洗濯機", "洗衣机", "洗衣機", "máy giặt"]),
        ("plaything", ["jouet", "おもちゃ", "玩具", "đồ chơi"]),
        ("swimming pool", ["piscine", "プール", "游泳池", "bể bơi"]),
        ("stool", ["tabouret", "スツール", "凳子", "ghế đẩu"]),
        ("barrel", ["tonneau", "樽", "桶", "thùng gỗ"]),
        ("basket", ["panier", "かご", "篮子", "籃子", "giỏ"]),
        ("waterfall", ["cascade", "滝", "瀑布", "thác nước"]),
        ("tent", ["tente", "テント", "帐篷", "帳篷", "lều"]),
        ("bag", ["sac", "handbag", "tote", "バッグ", "包", "túi"]),
        ("minibike", ["mini-moto", "ミニバイク", "迷你摩托车", "迷你摩托車", "xe máy mini"]),
        ("cradle", ["berceau", "揺りかご", "摇篮", "搖籃", "nôi"]),
        ("oven", ["four", "オーブン", "烤箱", "lò nướng"]),
        ("ball", ["ballon", "ボール", "球", "quả bóng"]),
        ("food", ["nourriture", "食べ物", "食物", "thức ăn"]),
        ("step", ["marche", "段差", "台阶", "台階", "bậc thềm"]),
        ("tank", ["réservoir", "タンク", "水箱", "bể chứa"]),
        ("trade name", ["nom commercial", "商標名", "商标名称", "商標名稱", "tên thương hiệu"]),
        ("microwave", ["micro-ondes", "電子レンジ", "微波炉", "微波爐", "lò vi sóng"]),
        ("pot", ["pot", "鉢", "锅", "鍋", "nồi"]),
        ("animal", ["animal", "動物", "动物", "động vật"]),
        ("bicycle", ["vélo", "自転車", "自行车", "自行車", "xe đạp"]),
        ("lake", ["lac", "湖", "hồ"]),
        ("dishwasher", ["lave-vaisselle", "食器洗い機", "洗碗机", "洗碗機", "máy rửa chén"]),
        ("screen", ["écran", "スクリーン", "屏幕", "màn hình"]),
        ("blanket", ["couverture", "毛布", "毯子", "chăn"]),
        ("sculpture", ["sculpture", "彫刻", "雕塑", "tượng điêu khắc"]),
        ("hood", ["hotte", "フード", "抽油烟机", "抽油煙機", "máy hút mùi"]),
        ("sconce", ["applique murale", "壁掛け照明", "壁灯", "壁燈", "đèn tường"]),
        ("vase", ["vase", "花瓶", "bình hoa"]),
        ("traffic light", ["feu de circulation", "信号機", "红绿灯", "紅綠燈", "đèn giao thông"]),
        ("tray", ["plateau", "トレイ", "托盘", "托盤", "khay"]),
        ("ashcan", ["poubelle", "ごみ箱", "垃圾桶", "thùng rác"]),
        ("fan", ["ventilateur", "扇風機", "风扇", "風扇", "quạt"]),
        ("pier", ["jetée", "桟橋", "码头", "碼頭", "cầu tàu"]),
        ("crt screen", ["écran cathodique", "ブラウン管画面", "显像管屏幕", "顯像管螢幕", "màn hình crt"]),
        ("plate", ["assiette", "皿", "盘子", "盤子", "đĩa"]),
        ("monitor", ["moniteur", "モニター", "显示器", "顯示器", "màn hình máy tính"]),
        ("bulletin board", ["tableau d'affichage", "掲示板", "公告栏", "公告欄", "bảng thông báo"]),
        ("shower", ["douche", "シャワー", "淋浴", "vòi sen"]),
        ("radiator", ["radiateur", "ラジエーター", "暖气片", "暖氣片", "bộ tản nhiệt"]),
        ("glass", ["verre", "ガラス", "玻璃", "kính"]),
        ("clock", ["horloge", "時計", "时钟", "時鐘", "đồng hồ"]),
        ("flag", ["drapeau", "旗", "lá cờ"])
    ]
}
