#!/usr/bin/env python3
"""Merge UI-visible interior room/style terms into Localizable.strings files."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCALIZABLE = ROOT / "AIHome" / "AIHome" / "Resources" / "Localizable"

LOCALE_FILES = [
    "en-US.lproj/Localizable.strings",
    "en.lproj/Localizable.strings",
    "ar-SA.lproj/Localizable.strings",
    "de-DE.lproj/Localizable.strings",
    "de.lproj/Localizable.strings",
    "es-ES.lproj/Localizable.strings",
    "es.lproj/Localizable.strings",
    "fr-FR.lproj/Localizable.strings",
    "fr.lproj/Localizable.strings",
    "hi.lproj/Localizable.strings",
    "id.lproj/Localizable.strings",
    "it.lproj/Localizable.strings",
    "ja.lproj/Localizable.strings",
    "ko.lproj/Localizable.strings",
    "ms.lproj/Localizable.strings",
    "pt-BR.lproj/Localizable.strings",
    "ru.lproj/Localizable.strings",
    "th.lproj/Localizable.strings",
    "tr.lproj/Localizable.strings",
]

# Only values shown in InteriorFlowViewModel.
ENGLISH: dict[str, str] = {
    "interior.room_type.dining_room": "Dining Room",
    "interior.room_type.bathroom": "Bathroom",
    "interior.room_type.bedroom": "Bedroom",
    "interior.room_type.home_office": "Home Office",
    "interior.room_type.study_room": "Study Room",
    "interior.room_type.coffee_shop": "Coffee Shop",
    "interior.room_type.living_room": "Living Room",
    "interior.room_type.kitchen": "Kitchen",
    "interior.room_type.restaurant": "Restaurant",
    "interior.room_type.gaming_room": "Gaming Room",
    "interior.room_type.attic": "Attic",
    "interior.room_type.office": "Office",
    "interior.room_type.balcony": "Balcony",
    "interior.design_style.no_style": "No Style",
    "interior.design_style.traditional": "Traditional",
    "interior.design_style.scandinavian": "Scandinavian",
    "interior.design_style.organic_modern": "Organic Modern",
    "interior.design_style.modern_farm_house": "Modern Farm House",
    "interior.design_style.modern": "Modern",
    "interior.design_style.minimalist": "Minimalist",
    "interior.design_style.japandi": "Japandi",
    "interior.design_style.vintage_eclectic": "Vintage Eclectic",
    "interior.design_style.tropical": "Tropical",
    "interior.design_style.rustic": "Rustic",
    "interior.design_style.quiet_luxury": "Quiet Luxury",
    "interior.design_style.maximalist": "Maximalist",
    "interior.design_style.luxurious": "Luxurious",
    "interior.design_style.industrial": "Industrial",
    "interior.design_style.midcentury_modern": "Midcentury Modern",
    "interior.design_style.contemporary": "Contemporary",
    "interior.design_style.coastal": "Coastal",
    "interior.design_style.biophilic": "Biophilic",
    "interior.design_style.scandi_boho": "Scandi Boho",
    "interior.design_style.retro": "Retro",
    "interior.design_style.neon": "Neon",
    "interior.design_style.modern_arabic": "Modern Arabic",
    "interior.design_style.mediterranean": "Mediterranean",
    "interior.design_style.kids_room": "Kids Room",
    "interior.design_style.desert_modernism": "Desert Modernism",
    "interior.design_style.christmas": "Christmas",
    "interior.design_style.candy_land": "Candy Land",
    "interior.design_style.brutalist": "Brutalist",
    "interior.design_style.art_deco": "Art Deco",
}

TRANSLATIONS: dict[str, dict[str, str]] = {
    "ar-SA": {
        "interior.room_type.dining_room": "غرفة الطعام",
        "interior.room_type.bathroom": "الحمام",
        "interior.room_type.bedroom": "غرفة النوم",
        "interior.room_type.home_office": "مكتب منزلي",
        "interior.room_type.study_room": "غرفة الدراسة",
        "interior.room_type.coffee_shop": "مقهى",
        "interior.room_type.living_room": "غرفة المعيشة",
        "interior.room_type.kitchen": "المطبخ",
        "interior.room_type.restaurant": "مطعم",
        "interior.room_type.gaming_room": "غرفة الألعاب",
        "interior.room_type.attic": "علّية",
        "interior.room_type.office": "مكتب",
        "interior.room_type.balcony": "شرفة",
        "interior.design_style.no_style": "بدون نمط",
        "interior.design_style.traditional": "تقليدي",
        "interior.design_style.scandinavian": "اسكندنافي",
        "interior.design_style.organic_modern": "حديث عضوي",
        "interior.design_style.modern_farm_house": "منزل ريفي حديث",
        "interior.design_style.modern": "حديث",
        "interior.design_style.minimalist": "مينيمالي",
        "interior.design_style.japandi": "جاباندي",
        "interior.design_style.vintage_eclectic": "انتقائي عتيق",
        "interior.design_style.tropical": "استوائي",
        "interior.design_style.rustic": "ريفي",
        "interior.design_style.quiet_luxury": "فخامة هادئة",
        "interior.design_style.maximalist": "ماكسيمالي",
        "interior.design_style.luxurious": "فاخر",
        "interior.design_style.industrial": "صناعي",
        "interior.design_style.midcentury_modern": "حديث منتصف القرن",
        "interior.design_style.contemporary": "معاصر",
        "interior.design_style.coastal": "ساحلي",
        "interior.design_style.biophilic": "Biophilic",
        "interior.design_style.scandi_boho": "سكاندي بوهو",
        "interior.design_style.retro": "ريترو",
        "interior.design_style.neon": "نيون",
        "interior.design_style.modern_arabic": "عربي حديث",
        "interior.design_style.mediterranean": "متوسطي",
        "interior.design_style.kids_room": "غرفة أطفال",
        "interior.design_style.desert_modernism": "حداثة صحراوية",
        "interior.design_style.christmas": "عيد الميلاد",
        "interior.design_style.candy_land": "أرض الحلوى",
        "interior.design_style.brutalist": "Brutalist",
        "interior.design_style.art_deco": "Art Deco",
    },
    "de": {
        "interior.room_type.dining_room": "Esszimmer",
        "interior.room_type.bathroom": "Badezimmer",
        "interior.room_type.bedroom": "Schlafzimmer",
        "interior.room_type.home_office": "Homeoffice",
        "interior.room_type.study_room": "Arbeitszimmer",
        "interior.room_type.coffee_shop": "Café",
        "interior.room_type.living_room": "Wohnzimmer",
        "interior.room_type.kitchen": "Küche",
        "interior.room_type.restaurant": "Restaurant",
        "interior.room_type.gaming_room": "Spielzimmer",
        "interior.room_type.attic": "Dachboden",
        "interior.room_type.office": "Büro",
        "interior.room_type.balcony": "Balkon",
        "interior.design_style.no_style": "Kein Stil",
        "interior.design_style.traditional": "Traditionell",
        "interior.design_style.scandinavian": "Skandinavisch",
        "interior.design_style.organic_modern": "Organisch Modern",
        "interior.design_style.modern_farm_house": "Modernes Farmhaus",
        "interior.design_style.modern": "Modern",
        "interior.design_style.minimalist": "Minimalistisch",
        "interior.design_style.japandi": "Japandi",
        "interior.design_style.vintage_eclectic": "Vintage Eklektisch",
        "interior.design_style.tropical": "Tropisch",
        "interior.design_style.rustic": "Rustikal",
        "interior.design_style.quiet_luxury": "Quiet Luxury",
        "interior.design_style.maximalist": "Maximalistisch",
        "interior.design_style.luxurious": "Luxuriös",
        "interior.design_style.industrial": "Industrial",
        "interior.design_style.midcentury_modern": "Mid-Century Modern",
        "interior.design_style.contemporary": "Zeitgenössisch",
        "interior.design_style.coastal": "Küstenstil",
        "interior.design_style.biophilic": "Biophil",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "Retro",
        "interior.design_style.neon": "Neon",
        "interior.design_style.modern_arabic": "Modern Arabisch",
        "interior.design_style.mediterranean": "Mediterran",
        "interior.design_style.kids_room": "Kinderzimmer",
        "interior.design_style.desert_modernism": "Desert Modernism",
        "interior.design_style.christmas": "Weihnachten",
        "interior.design_style.candy_land": "Candy Land",
        "interior.design_style.brutalist": "Brutalist",
        "interior.design_style.art_deco": "Art Deco",
    },
    "es": {
        "interior.room_type.dining_room": "Comedor",
        "interior.room_type.bathroom": "Baño",
        "interior.room_type.bedroom": "Dormitorio",
        "interior.room_type.home_office": "Oficina en casa",
        "interior.room_type.study_room": "Estudio",
        "interior.room_type.coffee_shop": "Cafetería",
        "interior.room_type.living_room": "Sala de estar",
        "interior.room_type.kitchen": "Cocina",
        "interior.room_type.restaurant": "Restaurante",
        "interior.room_type.gaming_room": "Sala de juegos",
        "interior.room_type.attic": "Ático",
        "interior.room_type.office": "Oficina",
        "interior.room_type.balcony": "Balcón",
        "interior.design_style.no_style": "Sin estilo",
        "interior.design_style.traditional": "Tradicional",
        "interior.design_style.scandinavian": "Escandinavo",
        "interior.design_style.organic_modern": "Moderno orgánico",
        "interior.design_style.modern_farm_house": "Casa de campo moderna",
        "interior.design_style.modern": "Moderno",
        "interior.design_style.minimalist": "Minimalista",
        "interior.design_style.japandi": "Japandi",
        "interior.design_style.vintage_eclectic": "Ecléctico vintage",
        "interior.design_style.tropical": "Tropical",
        "interior.design_style.rustic": "Rústico",
        "interior.design_style.quiet_luxury": "Lujo silencioso",
        "interior.design_style.maximalist": "Maximalista",
        "interior.design_style.luxurious": "Lujoso",
        "interior.design_style.industrial": "Industrial",
        "interior.design_style.midcentury_modern": "Mid-century modern",
        "interior.design_style.contemporary": "Contemporáneo",
        "interior.design_style.coastal": "Costero",
        "interior.design_style.biophilic": "Biofílico",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "Retro",
        "interior.design_style.neon": "Neón",
        "interior.design_style.modern_arabic": "Árabe moderno",
        "interior.design_style.mediterranean": "Mediterráneo",
        "interior.design_style.kids_room": "Habitación infantil",
        "interior.design_style.desert_modernism": "Modernismo desértico",
        "interior.design_style.christmas": "Navidad",
        "interior.design_style.candy_land": "Candy Land",
        "interior.design_style.brutalist": "Brutalista",
        "interior.design_style.art_deco": "Art Deco",
    },
    "fr": {
        "interior.room_type.dining_room": "Salle à manger",
        "interior.room_type.bathroom": "Salle de bain",
        "interior.room_type.bedroom": "Chambre",
        "interior.room_type.home_office": "Bureau à domicile",
        "interior.room_type.study_room": "Bureau d'étude",
        "interior.room_type.coffee_shop": "Café",
        "interior.room_type.living_room": "Salon",
        "interior.room_type.kitchen": "Cuisine",
        "interior.room_type.restaurant": "Restaurant",
        "interior.room_type.gaming_room": "Salle de jeux",
        "interior.room_type.attic": "Grenier",
        "interior.room_type.office": "Bureau",
        "interior.room_type.balcony": "Balcon",
        "interior.design_style.no_style": "Sans style",
        "interior.design_style.traditional": "Traditionnel",
        "interior.design_style.scandinavian": "Scandinave",
        "interior.design_style.organic_modern": "Moderne organique",
        "interior.design_style.modern_farm_house": "Ferme moderne",
        "interior.design_style.modern": "Moderne",
        "interior.design_style.minimalist": "Minimaliste",
        "interior.design_style.japandi": "Japandi",
        "interior.design_style.vintage_eclectic": "Éclectique vintage",
        "interior.design_style.tropical": "Tropical",
        "interior.design_style.rustic": "Rustique",
        "interior.design_style.quiet_luxury": "Luxe discret",
        "interior.design_style.maximalist": "Maximaliste",
        "interior.design_style.luxurious": "Luxueux",
        "interior.design_style.industrial": "Industriel",
        "interior.design_style.midcentury_modern": "Mid-century modern",
        "interior.design_style.contemporary": "Contemporain",
        "interior.design_style.coastal": "Côtier",
        "interior.design_style.biophilic": "Biophilique",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "Rétro",
        "interior.design_style.neon": "Néon",
        "interior.design_style.modern_arabic": "Arabe moderne",
        "interior.design_style.mediterranean": "Méditerranéen",
        "interior.design_style.kids_room": "Chambre d'enfant",
        "interior.design_style.desert_modernism": "Modernisme du désert",
        "interior.design_style.christmas": "Noël",
        "interior.design_style.candy_land": "Candy Land",
        "interior.design_style.brutalist": "Brutaliste",
        "interior.design_style.art_deco": "Art Deco",
    },
    "hi": {
        "interior.room_type.dining_room": "भोजन कक्ष",
        "interior.room_type.bathroom": "बाथरूम",
        "interior.room_type.bedroom": "शयनकक्ष",
        "interior.room_type.home_office": "होम ऑफिस",
        "interior.room_type.study_room": "अध्ययन कक्ष",
        "interior.room_type.coffee_shop": "कॉफ़ी शॉप",
        "interior.room_type.living_room": "लिविंग रूम",
        "interior.room_type.kitchen": "रसोई",
        "interior.room_type.restaurant": "रेस्तरां",
        "interior.room_type.gaming_room": "गेमिंग रूम",
        "interior.room_type.attic": "अटारी",
        "interior.room_type.office": "कार्यालय",
        "interior.room_type.balcony": "बालकनी",
        "interior.design_style.no_style": "कोई शैली नहीं",
        "interior.design_style.traditional": "पारंपरिक",
        "interior.design_style.scandinavian": "स्कैंडिनेवियाई",
        "interior.design_style.organic_modern": "ऑर्गेनिक मॉडर्न",
        "interior.design_style.modern_farm_house": "मॉडर्न फार्म हाउस",
        "interior.design_style.modern": "आधुनिक",
        "interior.design_style.minimalist": "मिनिमलिस्ट",
        "interior.design_style.japandi": "Japandi",
        "interior.design_style.vintage_eclectic": "विंटेज इक्लेक्टिक",
        "interior.design_style.tropical": "उष्णकटिबंधीय",
        "interior.design_style.rustic": "ग्रामीण",
        "interior.design_style.quiet_luxury": "शांत विलासिता",
        "interior.design_style.maximalist": "मैक्सिमलिस्ट",
        "interior.design_style.luxurious": "विलासी",
        "interior.design_style.industrial": "औद्योगिक",
        "interior.design_style.midcentury_modern": "मिड-सेंचुरी मॉडर्न",
        "interior.design_style.contemporary": "समकालीन",
        "interior.design_style.coastal": "तटीय",
        "interior.design_style.biophilic": "Biophilic",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "रेट्रो",
        "interior.design_style.neon": "नियॉन",
        "interior.design_style.modern_arabic": "आधुनिक अरबी",
        "interior.design_style.mediterranean": "भूमध्यसागरीय",
        "interior.design_style.kids_room": "बच्चों का कमरा",
        "interior.design_style.desert_modernism": "Desert Modernism",
        "interior.design_style.christmas": "क्रिसमस",
        "interior.design_style.candy_land": "Candy Land",
        "interior.design_style.brutalist": "Brutalist",
        "interior.design_style.art_deco": "Art Deco",
    },
    "id": {
        "interior.room_type.dining_room": "Ruang Makan",
        "interior.room_type.bathroom": "Kamar Mandi",
        "interior.room_type.bedroom": "Kamar Tidur",
        "interior.room_type.home_office": "Kantor Rumah",
        "interior.room_type.study_room": "Ruang Belajar",
        "interior.room_type.coffee_shop": "Kedai Kopi",
        "interior.room_type.living_room": "Ruang Tamu",
        "interior.room_type.kitchen": "Dapur",
        "interior.room_type.restaurant": "Restoran",
        "interior.room_type.gaming_room": "Ruang Gaming",
        "interior.room_type.attic": "Loteng",
        "interior.room_type.office": "Kantor",
        "interior.room_type.balcony": "Balkon",
        "interior.design_style.no_style": "Tanpa Gaya",
        "interior.design_style.traditional": "Tradisional",
        "interior.design_style.scandinavian": "Skandinavia",
        "interior.design_style.organic_modern": "Modern Organik",
        "interior.design_style.modern_farm_house": "Rumah Pertanian Modern",
        "interior.design_style.modern": "Modern",
        "interior.design_style.minimalist": "Minimalis",
        "interior.design_style.japandi": "Japandi",
        "interior.design_style.vintage_eclectic": "Eklektik Vintage",
        "interior.design_style.tropical": "Tropis",
        "interior.design_style.rustic": "Rustik",
        "interior.design_style.quiet_luxury": "Kemewahan Tenang",
        "interior.design_style.maximalist": "Maksimalis",
        "interior.design_style.luxurious": "Mewah",
        "interior.design_style.industrial": "Industrial",
        "interior.design_style.midcentury_modern": "Mid-Century Modern",
        "interior.design_style.contemporary": "Kontemporer",
        "interior.design_style.coastal": "Pantai",
        "interior.design_style.biophilic": "Biofilik",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "Retro",
        "interior.design_style.neon": "Neon",
        "interior.design_style.modern_arabic": "Arab Modern",
        "interior.design_style.mediterranean": "Mediterania",
        "interior.design_style.kids_room": "Kamar Anak",
        "interior.design_style.desert_modernism": "Desert Modernism",
        "interior.design_style.christmas": "Natal",
        "interior.design_style.candy_land": "Candy Land",
        "interior.design_style.brutalist": "Brutalist",
        "interior.design_style.art_deco": "Art Deco",
    },
    "it": {
        "interior.room_type.dining_room": "Sala da pranzo",
        "interior.room_type.bathroom": "Bagno",
        "interior.room_type.bedroom": "Camera da letto",
        "interior.room_type.home_office": "Ufficio domestico",
        "interior.room_type.study_room": "Studio",
        "interior.room_type.coffee_shop": "Caffè",
        "interior.room_type.living_room": "Soggiorno",
        "interior.room_type.kitchen": "Cucina",
        "interior.room_type.restaurant": "Ristorante",
        "interior.room_type.gaming_room": "Sala giochi",
        "interior.room_type.attic": "Soffitta",
        "interior.room_type.office": "Ufficio",
        "interior.room_type.balcony": "Balcone",
        "interior.design_style.no_style": "Nessuno stile",
        "interior.design_style.traditional": "Tradizionale",
        "interior.design_style.scandinavian": "Scandinavo",
        "interior.design_style.organic_modern": "Moderno organico",
        "interior.design_style.modern_farm_house": "Casa di campagna moderna",
        "interior.design_style.modern": "Moderno",
        "interior.design_style.minimalist": "Minimalista",
        "interior.design_style.japandi": "Japandi",
        "interior.design_style.vintage_eclectic": "Eclettico vintage",
        "interior.design_style.tropical": "Tropicale",
        "interior.design_style.rustic": "Rustico",
        "interior.design_style.quiet_luxury": "Lusso discreto",
        "interior.design_style.maximalist": "Massimalista",
        "interior.design_style.luxurious": "Lussuoso",
        "interior.design_style.industrial": "Industrial",
        "interior.design_style.midcentury_modern": "Mid-century modern",
        "interior.design_style.contemporary": "Contemporaneo",
        "interior.design_style.coastal": "Costiero",
        "interior.design_style.biophilic": "Biofilico",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "Retro",
        "interior.design_style.neon": "Neon",
        "interior.design_style.modern_arabic": "Arabo moderno",
        "interior.design_style.mediterranean": "Mediterraneo",
        "interior.design_style.kids_room": "Camera dei bambini",
        "interior.design_style.desert_modernism": "Desert Modernism",
        "interior.design_style.christmas": "Natale",
        "interior.design_style.candy_land": "Candy Land",
        "interior.design_style.brutalist": "Brutalista",
        "interior.design_style.art_deco": "Art Deco",
    },
    "ja": {
        "interior.room_type.dining_room": "ダイニングルーム",
        "interior.room_type.bathroom": "バスルーム",
        "interior.room_type.bedroom": "ベッドルーム",
        "interior.room_type.home_office": "ホームオフィス",
        "interior.room_type.study_room": "書斎",
        "interior.room_type.coffee_shop": "カフェ",
        "interior.room_type.living_room": "リビングルーム",
        "interior.room_type.kitchen": "キッチン",
        "interior.room_type.restaurant": "レストラン",
        "interior.room_type.gaming_room": "ゲームルーム",
        "interior.room_type.attic": "屋根裏",
        "interior.room_type.office": "オフィス",
        "interior.room_type.balcony": "バルコニー",
        "interior.design_style.no_style": "スタイルなし",
        "interior.design_style.traditional": "トラディショナル",
        "interior.design_style.scandinavian": "スカンジナビア",
        "interior.design_style.organic_modern": "オーガニックモダン",
        "interior.design_style.modern_farm_house": "モダンファームハウス",
        "interior.design_style.modern": "モダン",
        "interior.design_style.minimalist": "ミニマリスト",
        "interior.design_style.japandi": "ジャパンディ",
        "interior.design_style.vintage_eclectic": "ヴィンテージエクレクティック",
        "interior.design_style.tropical": "トロピカル",
        "interior.design_style.rustic": "ラスティック",
        "interior.design_style.quiet_luxury": "クワイエットラグジュアリー",
        "interior.design_style.maximalist": "マキシマリスト",
        "interior.design_style.luxurious": "ラグジュアリー",
        "interior.design_style.industrial": "インダストリアル",
        "interior.design_style.midcentury_modern": "ミッドセンチュリーモダン",
        "interior.design_style.contemporary": "コンテンポラリー",
        "interior.design_style.coastal": "コースタル",
        "interior.design_style.biophilic": "バイオフィリック",
        "interior.design_style.scandi_boho": "スカンディボホ",
        "interior.design_style.retro": "レトロ",
        "interior.design_style.neon": "ネオン",
        "interior.design_style.modern_arabic": "モダンアラビック",
        "interior.design_style.mediterranean": "地中海",
        "interior.design_style.kids_room": "キッズルーム",
        "interior.design_style.desert_modernism": "デザートモダニズム",
        "interior.design_style.christmas": "クリスマス",
        "interior.design_style.candy_land": "キャンディランド",
        "interior.design_style.brutalist": "ブルータリスト",
        "interior.design_style.art_deco": "アールデコ",
    },
    "ko": {
        "interior.room_type.dining_room": "다이닝룸",
        "interior.room_type.bathroom": "욕실",
        "interior.room_type.bedroom": "침실",
        "interior.room_type.home_office": "홈 오피스",
        "interior.room_type.study_room": "서재",
        "interior.room_type.coffee_shop": "카페",
        "interior.room_type.living_room": "거실",
        "interior.room_type.kitchen": "주방",
        "interior.room_type.restaurant": "레스토랑",
        "interior.room_type.gaming_room": "게임룸",
        "interior.room_type.attic": "다락방",
        "interior.room_type.office": "사무실",
        "interior.room_type.balcony": "발코니",
        "interior.design_style.no_style": "스타일 없음",
        "interior.design_style.traditional": "전통",
        "interior.design_style.scandinavian": "스칸디나비아",
        "interior.design_style.organic_modern": "오가닉 모던",
        "interior.design_style.modern_farm_house": "모던 팜하우스",
        "interior.design_style.modern": "모던",
        "interior.design_style.minimalist": "미니멀",
        "interior.design_style.japandi": "재팬디",
        "interior.design_style.vintage_eclectic": "빈티지 에클렉틱",
        "interior.design_style.tropical": "트로피컬",
        "interior.design_style.rustic": "러스틱",
        "interior.design_style.quiet_luxury": "조용한 럭셔리",
        "interior.design_style.maximalist": "맥시멀리스트",
        "interior.design_style.luxurious": "럭셔리",
        "interior.design_style.industrial": "인더스트리얼",
        "interior.design_style.midcentury_modern": "미드센추리 모던",
        "interior.design_style.contemporary": "컨템포러리",
        "interior.design_style.coastal": "해안",
        "interior.design_style.biophilic": "바이오필릭",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "레트로",
        "interior.design_style.neon": "네온",
        "interior.design_style.modern_arabic": "모던 아랍",
        "interior.design_style.mediterranean": "지중해",
        "interior.design_style.kids_room": "키즈룸",
        "interior.design_style.desert_modernism": "사막 모더니즘",
        "interior.design_style.christmas": "크리스마스",
        "interior.design_style.candy_land": "캔디랜드",
        "interior.design_style.brutalist": "브루탈리스트",
        "interior.design_style.art_deco": "아르데코",
    },
    "ms": {
        "interior.room_type.dining_room": "Ruang Makan",
        "interior.room_type.bathroom": "Bilik Mandi",
        "interior.room_type.bedroom": "Bilik Tidur",
        "interior.room_type.home_office": "Pejabat Rumah",
        "interior.room_type.study_room": "Bilik Belajar",
        "interior.room_type.coffee_shop": "Kedai Kopi",
        "interior.room_type.living_room": "Ruang Tamu",
        "interior.room_type.kitchen": "Dapur",
        "interior.room_type.restaurant": "Restoran",
        "interior.room_type.gaming_room": "Bilik Permainan",
        "interior.room_type.attic": "Loteng",
        "interior.room_type.office": "Pejabat",
        "interior.room_type.balcony": "Balkoni",
        "interior.design_style.no_style": "Tiada Gaya",
        "interior.design_style.traditional": "Tradisional",
        "interior.design_style.scandinavian": "Skandinavia",
        "interior.design_style.organic_modern": "Moden Organik",
        "interior.design_style.modern_farm_house": "Rumah Ladang Moden",
        "interior.design_style.modern": "Moden",
        "interior.design_style.minimalist": "Minimalis",
        "interior.design_style.japandi": "Japandi",
        "interior.design_style.vintage_eclectic": "Eklektik Vintaj",
        "interior.design_style.tropical": "Tropika",
        "interior.design_style.rustic": "Rustik",
        "interior.design_style.quiet_luxury": "Kemewahan Senyap",
        "interior.design_style.maximalist": "Maksimalis",
        "interior.design_style.luxurious": "Mewah",
        "interior.design_style.industrial": "Industrial",
        "interior.design_style.midcentury_modern": "Mid-Century Modern",
        "interior.design_style.contemporary": "Kontemporari",
        "interior.design_style.coastal": "Pantai",
        "interior.design_style.biophilic": "Biofilik",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "Retro",
        "interior.design_style.neon": "Neon",
        "interior.design_style.modern_arabic": "Arab Moden",
        "interior.design_style.mediterranean": "Mediterranean",
        "interior.design_style.kids_room": "Bilik Kanak-kanak",
        "interior.design_style.desert_modernism": "Desert Modernism",
        "interior.design_style.christmas": "Krismas",
        "interior.design_style.candy_land": "Candy Land",
        "interior.design_style.brutalist": "Brutalist",
        "interior.design_style.art_deco": "Art Deco",
    },
    "pt-BR": {
        "interior.room_type.dining_room": "Sala de jantar",
        "interior.room_type.bathroom": "Banheiro",
        "interior.room_type.bedroom": "Quarto",
        "interior.room_type.home_office": "Escritório em casa",
        "interior.room_type.study_room": "Sala de estudo",
        "interior.room_type.coffee_shop": "Cafeteria",
        "interior.room_type.living_room": "Sala de estar",
        "interior.room_type.kitchen": "Cozinha",
        "interior.room_type.restaurant": "Restaurante",
        "interior.room_type.gaming_room": "Sala de jogos",
        "interior.room_type.attic": "Sótão",
        "interior.room_type.office": "Escritório",
        "interior.room_type.balcony": "Varanda",
        "interior.design_style.no_style": "Sem estilo",
        "interior.design_style.traditional": "Tradicional",
        "interior.design_style.scandinavian": "Escandinavo",
        "interior.design_style.organic_modern": "Moderno orgânico",
        "interior.design_style.modern_farm_house": "Casa de campo moderna",
        "interior.design_style.modern": "Moderno",
        "interior.design_style.minimalist": "Minimalista",
        "interior.design_style.japandi": "Japandi",
        "interior.design_style.vintage_eclectic": "Eclético vintage",
        "interior.design_style.tropical": "Tropical",
        "interior.design_style.rustic": "Rústico",
        "interior.design_style.quiet_luxury": "Luxo discreto",
        "interior.design_style.maximalist": "Maximalista",
        "interior.design_style.luxurious": "Luxuoso",
        "interior.design_style.industrial": "Industrial",
        "interior.design_style.midcentury_modern": "Mid-century modern",
        "interior.design_style.contemporary": "Contemporâneo",
        "interior.design_style.coastal": "Costeiro",
        "interior.design_style.biophilic": "Biofílico",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "Retrô",
        "interior.design_style.neon": "Neon",
        "interior.design_style.modern_arabic": "Árabe moderno",
        "interior.design_style.mediterranean": "Mediterrâneo",
        "interior.design_style.kids_room": "Quarto infantil",
        "interior.design_style.desert_modernism": "Desert Modernism",
        "interior.design_style.christmas": "Natal",
        "interior.design_style.candy_land": "Candy Land",
        "interior.design_style.brutalist": "Brutalista",
        "interior.design_style.art_deco": "Art Deco",
    },
    "ru": {
        "interior.room_type.dining_room": "Столовая",
        "interior.room_type.bathroom": "Ванная",
        "interior.room_type.bedroom": "Спальня",
        "interior.room_type.home_office": "Домашний офис",
        "interior.room_type.study_room": "Кабинет",
        "interior.room_type.coffee_shop": "Кофейня",
        "interior.room_type.living_room": "Гостиная",
        "interior.room_type.kitchen": "Кухня",
        "interior.room_type.restaurant": "Ресторан",
        "interior.room_type.gaming_room": "Игровая комната",
        "interior.room_type.attic": "Чердак",
        "interior.room_type.office": "Офис",
        "interior.room_type.balcony": "Балкон",
        "interior.design_style.no_style": "Без стиля",
        "interior.design_style.traditional": "Традиционный",
        "interior.design_style.scandinavian": "Скandinavian",
        "interior.design_style.organic_modern": "Органический модерн",
        "interior.design_style.modern_farm_house": "Современный farmhouse",
        "interior.design_style.modern": "Современный",
        "interior.design_style.minimalist": "Минимализм",
        "interior.design_style.japandi": "Japandi",
        "interior.design_style.vintage_eclectic": "Винтажный эклектик",
        "interior.design_style.tropical": "Тропический",
        "interior.design_style.rustic": "Деревенский",
        "interior.design_style.quiet_luxury": "Тихая роскошь",
        "interior.design_style.maximalist": "Максимализм",
        "interior.design_style.luxurious": "Роскошный",
        "interior.design_style.industrial": "Индustrial",
        "interior.design_style.midcentury_modern": "Mid-century modern",
        "interior.design_style.contemporary": "Современный",
        "interior.design_style.coastal": "Прибрежный",
        "interior.design_style.biophilic": "Биофильный",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "Ретро",
        "interior.design_style.neon": "Неон",
        "interior.design_style.modern_arabic": "Современный арабский",
        "interior.design_style.mediterranean": "Средиземноморский",
        "interior.design_style.kids_room": "Детская",
        "interior.design_style.desert_modernism": "Desert Modernism",
        "interior.design_style.christmas": "Рождество",
        "interior.design_style.candy_land": "Candy Land",
        "interior.design_style.brutalist": "Brutalist",
        "interior.design_style.art_deco": "Art Deco",
    },
    "th": {
        "interior.room_type.dining_room": "ห้องรับประทานอาหาร",
        "interior.room_type.bathroom": "ห้องน้ำ",
        "interior.room_type.bedroom": "ห้องนอน",
        "interior.room_type.home_office": "ออฟฟิศที่บ้าน",
        "interior.room_type.study_room": "ห้องเรียน",
        "interior.room_type.coffee_shop": "ร้านกาแฟ",
        "interior.room_type.living_room": "ห้องนั่งเล่น",
        "interior.room_type.kitchen": "ครัว",
        "interior.room_type.restaurant": "ร้านอาหาร",
        "interior.room_type.gaming_room": "ห้องเกม",
        "interior.room_type.attic": "ห้องใต้หลังคา",
        "interior.room_type.office": "สำนักงาน",
        "interior.room_type.balcony": "ระเบียง",
        "interior.design_style.no_style": "ไม่มีสไตล์",
        "interior.design_style.traditional": "ดั้งเดิม",
        "interior.design_style.scandinavian": "สแกandinavian",
        "interior.design_style.organic_modern": "โมเดิร์นออร์แกนิก",
        "interior.design_style.modern_farm_house": "Modern Farm House",
        "interior.design_style.modern": "โมเดิร์น",
        "interior.design_style.minimalist": "มินิมอล",
        "interior.design_style.japandi": "Japandi",
        "interior.design_style.vintage_eclectic": "วintage Eclectic",
        "interior.design_style.tropical": "ทropical",
        "interior.design_style.rustic": "รustic",
        "interior.design_style.quiet_luxury": "Quiet Luxury",
        "interior.design_style.maximalist": "Maximalist",
        "interior.design_style.luxurious": "หรูหรา",
        "interior.design_style.industrial": "Industrial",
        "interior.design_style.midcentury_modern": "Midcentury Modern",
        "interior.design_style.contemporary": "ร่วมสมัย",
        "interior.design_style.coastal": "Coastal",
        "interior.design_style.biophilic": "Biophilic",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "Retro",
        "interior.design_style.neon": "Neon",
        "interior.design_style.modern_arabic": "Modern Arabic",
        "interior.design_style.mediterranean": "Mediterranean",
        "interior.design_style.kids_room": "ห้องเด็ก",
        "interior.design_style.desert_modernism": "Desert Modernism",
        "interior.design_style.christmas": "คริสต์มาส",
        "interior.design_style.candy_land": "Candy Land",
        "interior.design_style.brutalist": "Brutalist",
        "interior.design_style.art_deco": "Art Deco",
    },
    "tr": {
        "interior.room_type.dining_room": "Yemek Odası",
        "interior.room_type.bathroom": "Banyo",
        "interior.room_type.bedroom": "Yatak Odası",
        "interior.room_type.home_office": "Ev Ofisi",
        "interior.room_type.study_room": "Çalışma Odası",
        "interior.room_type.coffee_shop": "Kahve Dükkanı",
        "interior.room_type.living_room": "Oturma Odası",
        "interior.room_type.kitchen": "Mutfak",
        "interior.room_type.restaurant": "Restoran",
        "interior.room_type.gaming_room": "Oyun Odası",
        "interior.room_type.attic": "Tavan Arası",
        "interior.room_type.office": "Ofis",
        "interior.room_type.balcony": "Balkon",
        "interior.design_style.no_style": "Stil Yok",
        "interior.design_style.traditional": "Geleneksel",
        "interior.design_style.scandinavian": "İskandinav",
        "interior.design_style.organic_modern": "Organik Modern",
        "interior.design_style.modern_farm_house": "Modern Çiftlik Evi",
        "interior.design_style.modern": "Modern",
        "interior.design_style.minimalist": "Minimalist",
        "interior.design_style.japandi": "Japandi",
        "interior.design_style.vintage_eclectic": "Vintage Eklektik",
        "interior.design_style.tropical": "Tropikal",
        "interior.design_style.rustic": "Rustik",
        "interior.design_style.quiet_luxury": "Sessiz Lüks",
        "interior.design_style.maximalist": "Maksimalist",
        "interior.design_style.luxurious": "Lüks",
        "interior.design_style.industrial": "Endüstriyel",
        "interior.design_style.midcentury_modern": "Mid-Century Modern",
        "interior.design_style.contemporary": "Çağdaş",
        "interior.design_style.coastal": "Kıyı",
        "interior.design_style.biophilic": "Biyofilik",
        "interior.design_style.scandi_boho": "Scandi Boho",
        "interior.design_style.retro": "Retro",
        "interior.design_style.neon": "Neon",
        "interior.design_style.modern_arabic": "Modern Arap",
        "interior.design_style.mediterranean": "Akdeniz",
        "interior.design_style.kids_room": "Çocuk Odası",
        "interior.design_style.desert_modernism": "Desert Modernism",
        "interior.design_style.christmas": "Noel",
        "interior.design_style.candy_land": "Candy Land",
        "interior.design_style.brutalist": "Brutalist",
        "interior.design_style.art_deco": "Art Deco",
    },
}


def locale_key(path: str) -> str:
    folder = Path(path).parts[0].replace(".lproj", "")
    if folder in {"en-US", "en"}:
        return "en"
    if folder in {"de-DE", "de"}:
        return "de"
    if folder in {"es-ES", "es"}:
        return "es"
    if folder in {"fr-FR", "fr"}:
        return "fr"
    return folder


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def format_block(terms: dict[str, str]) -> str:
    lines = ["\n/* Interior flow UI terms */"]
    for key, value in terms.items():
        lines.append(f'"{key}" = "{escape(value)}";')
    return "\n".join(lines) + "\n"


def merge_file(relative_path: str) -> None:
    file_path = LOCALIZABLE / relative_path
    content = file_path.read_text(encoding="utf-8")

    for key in ENGLISH:
        content = re.sub(rf'^"{re.escape(key)}" = ".*";\n', "", content, flags=re.MULTILINE)
    content = re.sub(r"\n?/\* Interior flow UI terms \*/\n", "\n", content)

    locale = locale_key(relative_path)
    terms = ENGLISH if locale == "en" else TRANSLATIONS.get(locale, ENGLISH)
    block = format_block(terms)

    match = re.search(r'"interior_flow\.pick_design_style" = "[^"]+";\n', content)
    if not match:
        raise RuntimeError(f"Could not locate interior_flow anchor in {relative_path}")

    insert_at = match.end()
    content = content[:insert_at] + block + content[insert_at:]
    file_path.write_text(content, encoding="utf-8")
    print(f"updated {relative_path}")


def main() -> None:
    for relative_path in LOCALE_FILES:
        merge_file(relative_path)
    print(f"done: {len(ENGLISH)} keys x {len(LOCALE_FILES)} locales")


if __name__ == "__main__":
    main()
