import Foundation
import UIKit

struct InteriorDraft {
    var sourceImage: UIImage?
    var roomType: InteriorRoomType?
    var customStyle: String?
    var designStyle: InteriorDesignStyle?
    var intervention: UIInterventionLevel?
}

enum InteriorStep: Int, CaseIterable {
    case photoSelection = 1
    case roomType = 2
    case designStyle = 3
    case intervention = 4
}

enum InteriorRoomType: String, CaseIterable, Identifiable {
    case livingRoom = "Living Room"
    case bedroom = "Bedroom"
    case bathroom = "Bathroom"
    case kitchen = "Kitchen"
    case diningRoom = "Dining Room"
    case attic = "Attic"
    case studyRoom = "Study Room"
    case homeOffice = "Home Office"
    case familyRoom = "Family Room"
    case formalDiningRoom = "Formal Dining Room"
    case homeTheater = "Home Theater"
    case kidsRoom = "Kids Room"
    case balcony = "Balcony"
    case gamingRoom = "Gaming Room"
    case meetingRoom = "Meeting Room"
    case workshop = "Workshop"
    case fitnessGym = "Fitness Gym"
    case coffeeShop = "Coffee Shop"
    case clothingStore = "Clothing Store"
    case restaurant = "Restaurant"
    case office = "Office"
    case coworkingSpace = "Coworking Space"
    case hotelLobby = "Hotel Lobby"
    case hotelRoom = "Hotel Room"
    case hotelBathroom = "Hotel Bathroom"
    case exhibitionSpace = "Exhibition Space"
    case onsen = "Onsen"
    case workingSpace = "Working Space"
    case wineCellar = "Wine Cellar"
    case rooftopTerrace = "Rooftop Terrace"
    case sunroom = "Sunroom"
    case homeSpa = "Home Spa"
    case mudroom = "Mudroom"
    case craftRoom = "Craft Room"
    case dressingRoom = "Dressing Room"
    case guestBedroom = "Guest Bedroom"
    case homeBar = "Home Bar"
    case library = "Library"
    case artStudio = "Art Studio"
    case yogaStudio = "Yoga Studio"
    case photoStudio = "Photo Studio"
    case multimediaRoom = "Multimedia Room"
    case auditorium = "Auditorium"
    case medicalExamRoom = "Medical Exam Room"
    case receptionArea = "Reception Area"
    case musicRoom = "Music Room"
    case scienceLaboratory = "Science Laboratory"
    case weddingRoom = "Wedding Room"
    case laundryRoom = "Laundry Room"
    case outdoorKitchen = "Outdoor Kitchen"
    case utilityRoom = "Utility Room"
    case petRoom = "Pet Room"
    case homeGym = "Home Gym"
    case lounge = "Lounge"
    case walkInCloset = "Walk In Closet"
    case playroom = "Playroom"
    case readingNook = "Reading Nook"
    case sauna = "Sauna"
    case manCave = "Man Cave"
    case foyer = "Foyer"
    case greenhouse = "Greenhouse"
    case sheShed = "She Shed"
    case conservatory = "Conservatory"
    case nursery = "Nursery"
    case prayerRoom = "Prayer Room"
    case openKitchenLivingRoom = "Open Kitchen Living Room"
    case hallway = "Hallway"
    case homeObservatory = "Home Observatory"
    case secretRoom = "Secret Room"
    case massageRoom = "Massage Room"
    case shoeCloset = "Shoe Closet"
    case petBedroom = "Pet Bedroom"
    case homeRecordingStudio = "Home Recording Studio"
    case meditationRoom = "Meditation Room"
    case homeTattooStudio = "Home Tattoo Studio"
    case indoorGarden = "Indoor Garden"
    case basementLounge = "Basement Lounge"
    case gameRoom = "Game Room"
    case homeBrewery = "Home Brewery"
    case cigarLounge = "Cigar Lounge"
    case billiardRoom = "Billiard Room"
    case sunPorch = "Sun Porch"
    case solarium = "Solarium"
    case vrRoom = "Vr Room"
    case aquariumRoom = "Aquarium Room"
    case boardGameRoom = "Board Game Room"
    case petGroomingRoom = "Pet Grooming Room"
    case petPlayroom = "Pet Playroom"
    case craftBrewery = "Craft Brewery"
    case homeLaboratory = "Home Laboratory"
    case darkroom = "Darkroom"
    case seasonalStorageRoom = "Seasonal Storage Room"
    case modelBuildingRoom = "Model Building Room"
    case indoorPlayground = "Indoor Playground"
    case tatamiRoom = "Tatami Room"
    case childrensArtRoom = "Childrens Art Room"
    case petBoardingRoom = "Pet Boarding Room"
    case greenRoofAccessRoom = "Green Roof Access Room"
    case linenCloset = "Linen Closet"
    case trophyRoom = "Trophy Room"
    case garageGym = "Garage Gym"
    case homeSecurityRoom = "Home Security Room"
    case rumpusRoom = "Rumpus Room"
    case hobbyRoom = "Hobby Room"
    case outdoorShowerArea = "Outdoor Shower Area"
    case dogWashingStation = "Dog Washing Station"
    case courtyardWithSeatingArea = "Courtyard With Seating Area"
    case homeSalon = "Home Salon"
    case herbGardenRoom = "Herb Garden Room"
    case wineBarRoom = "Wine Bar Room"
    case orangery = "Orangery"
    case sculptureStudio = "Sculpture Studio"
    case greenhouseAtrium = "Greenhouse Atrium"
    case mezzanineLibrary = "Mezzanine Library"
    case personalRetreatRoom = "Personal Retreat Room"
    case techControlRoom = "Tech Control Room"
    case teaRoom = "Tea Room"

    var id: String { rawValue }
}

enum InteriorDesignStyle: String, CaseIterable, Identifiable {
    case noStyle = "No Style"
    case eclectic = "Eclectic"
    case modern = "Modern"
    case contemporary = "Contemporary"
    case transitional = "Transitional"
    case scandinavian = "Scandinavian"
    case mediterranean = "Mediterranean"
    case ikea = "Ikea"
    case industrial = "Industrial"
    case kidsRoom = "Kids Room"
    case shabbyChic = "Shabby Chic"
    case coastal = "Coastal"
    case bauhaus = "Bauhaus"
    case bohemian = "Bohemian"
    case traditional = "Traditional"
    case rustic = "Rustic"
    case minimalism = "Minimalism"
    case japandi = "Japandi"
    case japaneseDesign = "Japanese Design"
    case modernArabic = "Modern Arabic"
    case traditionalArabic = "Traditional Arabic"
    case bali = "Bali"
    case tropical = "Tropical"
    case asianDecor = "Asian Decor"
    case zen = "Zen"
    case hollywoodRegency = "Hollywood Regency"
    case hollywoodGlam = "Hollywood Glam"
    case minimalist = "Minimalist"
    case christmas = "Christmas"
    case futuristic = "Futuristic"
    case luxurious = "Luxurious"
    case midcenturyModern = "Midcentury Modern"
    case biophilic = "Biophilic"
    case cottageCore = "Cottage Core"
    case frenchCountry = "French Country"
    case artDeco = "Art Deco"
    case artNouveau = "Art Nouveau"
    case southWestern = "South Western"
    case modernFarmHouse = "Modern Farm House"
    case moroccan = "Moroccan"
    case gothic = "Gothic"
    case victorian = "Victorian"
    case steampunk = "Steampunk"
    case urbanModern = "Urban Modern"
    case desertModernism = "Desert Modernism"
    case colonial = "Colonial"
    case brutalist = "Brutalist"
    case nordicNoir = "Nordic Noir"
    case postmodern = "Postmodern"
    case psychedelic = "Psychedelic"
    case cosmicChic = "Cosmic Chic"
    case mexicanHacienda = "Mexican Hacienda"
    case coastalModern = "Coastal Modern"
    case ecoFriendly = "Eco Friendly"
    case popArt = "Pop Art"
    case vintageGlam = "Vintage Glam"
    case candyLand = "Candy Land"
    case airbnb = "Airbnb"
    case glamRock = "Glam Rock"
    case barbie = "Barbie"
    case doodle = "Doodle"
    case sketch = "Sketch"
    case maximalist = "Maximalist"
    case professional = "Professional"
    case halloween = "Halloween"
    case retro = "Retro"
    case romantic = "Romantic"
    case safari = "Safari"
    case tuscan = "Tuscan"
    case nautical = "Nautical"
    case craftman = "Craftman"
    case farmhouseChic = "Farmhouse Chic"
    case prairie = "Prairie"
    case cubism = "Cubism"
    case quietLuxury = "Quiet Luxury"
    case baroque = "Baroque"
    case neoclassical = "Neoclassical"
    case rococo = "Rococo"
    case georgian = "Georgian"
    case edwardian = "Edwardian"
    case tudorRevival = "Tudor Revival"
    case renaissanceRevival = "Renaissance Revival"
    case americanCraftsman = "American Craftsman"
    case missionRevival = "Mission Revival"
    case deconstructivism = "Deconstructivism"
    case grecianRevival = "Grecian Revival"
    case regency = "Regency"
    case highTech = "High Tech"
    case islamicDesign = "Islamic Design"
    case oriental = "Oriental"
    case artisan = "Artisan"
    case preRaphaelite = "Pre Raphaelite"
    case expressionist = "Expressionist"
    case biedermeier = "Biedermeier"
    case gustavian = "Gustavian"
    case greekRevival = "Greek Revival"
    case hygge = "Hygge"
    case organicModern = "Organic Modern"
    case neon = "Neon"
    case memphis = "Memphis"
    case savannahStyle = "Savannah Style"
    case flemish = "Flemish"
    case scandiBoho = "Scandi Boho"
    case parisianChic = "Parisian Chic"
    case industrialGlam = "Industrial Glam"
    case californiaCasual = "California Casual"
    case southBeach = "South Beach"
    case vintageEclectic = "Vintage Eclectic"
    case gardenStyle = "Garden Style"
    case contemporaryRustic = "Contemporary Rustic"
    case meditativeMinimalism = "Meditative Minimalism"
    case victorianGothic = "Victorian Gothic"
    case highVictorian = "High Victorian"
    case imperialRussian = "Imperial Russian"
    case frenchProvincial = "French Provincial"

    var id: String { rawValue }

    var prompt: String? {
        switch self {
        case .transitional: return "A stunning portrait orientation interior of a transitional kitchen. Light grey shaker cabinets, a classic marble slab backsplash, modern polished nickel hardware, and high-end stainless steel appliances. Warm oak floors, bright and airy lighting, crisp professional architectural photography."
        case .traditional: return "A portrait architectural photo of an elegant traditional living room. Rich dark walnut wall paneling, a classic brick fireplace, a plush velvet tufted sofa, and a vintage Persian rug. Inset custom bookshelves filled with old books, warm ambient lamplight, stately and timeless, vertical composition."
        case .scandinavian: return "A minimalist Scandinavian bedroom interior, portrait shot. Light pine wood platform bed with layered neutral linen bedding. Large windows with sheer curtains letting in soft morning sunlight. A functional sleek wooden nightstand, a single green potted plant, bright, calm, airy, 9:16 aspect ratio."
        case .organicModern: return "A vertical composition of an organic modern living room. Features a soft curved cream sofa, a raw edge travertine coffee table, and texturized plaster walls. Warm oak accents, boucle fabrics, natural jute rug, large fiddle leaf fig plant in a clay pot, soft daylight, warm earth tones."
        case .modernFarmHouse: return "A bright portrait perspective of a modern farmhouse kitchen. Exposed rustic wooden ceiling beams, white vertical shiplap walls, a large porcelain apron-front farmhouse sink, matte black fixtures, and a white oak island with woven counter stools. Cozy, clean, sunny interior visualization."
        case .modern: return "A sleek modern bedroom captured in a portrait shot. High-end low-profile platform bed, floor-to-ceiling glass windows overlooking a city skyline at dusk. Clean architectural lines, an accent wall made of dark polished concrete, hidden LED strip lighting, high-end look, vertical frame."
        case .minimalist: return "An ultra-minimalist living room, vertical architectural shot. A single low-slung neutral fabric sofa, a monolithic polished concrete block coffee table, completely empty smooth white walls. Perfect shadows cast by soft natural light from a side window, peaceful, silent, clutter-free."
        case .japandi: return "A beautiful Japandi style kitchen, portrait view. Smooth light oak flat-panel cabinetry paired with dark matte black plumbing fixtures. A minimalist slatted wood island, simple ceramic vases with delicate dried branches, low-contrast, tranquil, blending Japanese and Nordic styles."
        case .vintageEclectic: return "A vibrant vintage eclectic bedroom, portrait format. A mix of midcentury modern dresser, an antique ornate gold-framed wall mirror, a colorful gallery wall with mismatched art prints, and a cozy patterned duvet cover. Funky, highly curated, rich personal character."
        case .tropical: return "A tropical resort-style living room interior, portrait framing. Massive open bi-fold doors leading directly to a lush green garden patio. Exotic teak wood furniture, large fan palm leaves in oversized terracotta pots, woven rattan light fixtures, bright balmy island breeze feel."
        case .rustic: return "A cozy rustic bedroom inside a log cabin, portrait angle. Heavy exposed hand-hewn logs form the walls and ceiling. A sturdy stone fireplace with a crackling fire, a thick wool plaid blanket thrown over a dark wood bed frame, warm cabin glow, comforting, intimate ambiance."
        case .quietLuxury: return "An exquisite quiet luxury kitchen, portrait composition. Seamless custom cabinetry with hidden hardware, a massive island made of rare Calacatta marble with striking veins. Understated premium materials, unlacquered brass details, soft natural museum-grade spotlighting."
        case .maximalist: return "A high-pigment maximalist living room, portrait view. Moody emerald green color-drenched walls covered in bold tropical wallpaper. Rich velvet jewel-toned seating, layered eclectic rugs, dense gallery wall filling every space, gold accents, dramatic, artsy, confident style."
        case .luxurious: return "A glamorous luxurious bedroom, portrait frame. An oversized tufted velvet headboard reaching to the ceiling, high-gloss lacquered surfaces, a dazzling crystal chandelier casting soft reflections, silk sheets, and polished marble flooring with a plush faux-fur area rug."
        case .industrial: return "An industrial loft kitchen, portrait perspective. Exposed red brick accent walls, black steel structural beams, and concrete countertops. Open industrial pipe shelving holding glassware, pendant factory warehouse lights hanging over a stainless steel island, edgy urban style."
        case .midcenturyModern: return "A classic midcentury modern living room, vertical layout. An iconic walnut sideboard, a caramel leather lounge chair with tapered wooden legs, geometric retro abstract area rug, and atomic era lighting. Warm wood tones, authentic retro style, sunlit room."
        case .contemporary: return "A cutting-edge contemporary kitchen, portrait orientation. Sleek high-gloss flat-front cabinets in a bold navy blue, integrated smart appliances, a clean white quartz waterfall countertop, and sculptural modern pendant lighting. Fresh, high-end retail look."
        case .coastal: return "A breezy coastal bedroom, portrait photography. Soft white and seafoam blue color palette, light-washed driftwood furniture, subtle beige linen fabrics, and a jute rug. Large open windows letting in clear seaside afternoon sunlight, relaxed beachside aesthetic."
        case .biophilic: return "A biophilic living room design oasis, vertical framing. A stunning floor-to-ceiling living green wall overflowing with tropical ferns and vines. Skylights flooding the room with bright sunshine, light natural oak furniture, a serene environment integrated with nature."
        case .scandiBoho: return "A cozy Scandi Boho bedroom, portrait layout. Clean white walls and minimalist layout combined with rich Bohemian textures: macro macrame wall hangings, layered moroccan shag rugs, fluffy pampas grass in ceramic pots, and soft ivory textiles. Warm and inviting."
        case .retro: return "A nostalgic 1970s retro living room, portrait orientation. A curved avocado green sofa, bold orange and brown psychedelic wallpaper, a shag carpet, and a vintage vinyl record player console. Warm groovy tones, soft atmospheric vintage filter feel."
        case .neon: return "An electric neon-soaked bedroom interior, vertical portrait view. A high-tech gaming setup, walls lined with vibrant pink and cyan LED light strips, custom glowing kanji signs. Sleek modern black furniture reflecting the colorful neon ambient light, futuristic gamer lounge."
        case .modernArabic: return "A majestic modern Arabic living room, portrait view. Features clean contemporary geometry seamlessly integrated with elegant mashrabiya wood screens. Low-profile deep luxury seating, intricate warm gold metallic light fixtures casting geometric patterns on the walls."
        case .mediterranean: return "A sun-drenched Mediterranean kitchen, portrait format. Textured white lime-washed plaster walls, beautiful terracotta floor tiles, sweeping architectural arches, and exposed rustic wood beams. Olive branches in a clay jug on a stone countertop, warm and organic."
        case .kidsRoom: return "A playful and creative kids bedroom, portrait shot. A custom built-in wooden loft bed with a built-in play fort underneath. Soft whimsical pastel accent walls, cozy reading nook with mountain-shaped pillows, clean organized toy storage baskets, bright and cheerful."
        case .desertModernism: return "A stunning portrait orientation interior of a luxury Desert Modernism living room. Low-profile midcentury furniture, raw stacked stone accent walls, warm cedar wood ceilings, and large terrazzo tile floors. A seamless wall of floor-to-ceiling glass reveals a panoramic view of a Joshua Tree desert landscape at golden hour sunset. Warm, dusty ochre, sage, and sand color palette. Minimalist luxury, high-end architectural photography, cinematic soft sunlight, 3:4 aspect ratio, vertical composition."
        case .christmas: return "A cozy Christmas themed living room, portrait framing. A magnificent tall pine tree glowing with warm fairy lights and beautiful red and gold ornaments. A roaring fire in a classic white brick fireplace, stockings hanging from the mantel, heavy knit blankets, festive holiday warmth."
        case .candyLand: return "A whimsical Candy Land inspired kitchen, portrait layout. Soft pastel pink shaker cabinets, mint green walls, a playful lavender herringbone tile backsplash, and golden drawer pulls resembling sweet treats. Magical, fun, dopamine decor aesthetic, cheerful lighting."
        case .brutalist: return "A monumental brutalist bedroom design, vertical perspective. Raw, unpolished board-formed concrete walls, massive blocky geometric concrete architecture, a minimal low platform bed with charcoal grey linens. Moody casting shadows, dramatic and architectural."
        case .artDeco: return "A stunning Art Deco living room, portrait framing. Features a rich velvet fan-back sofa, bold black and gold geometric wall panels, a polished brass bar cart, and glossy marble floors. Lavish, glamorous, high-contrast symmetry, classic 1920s luxury redefined."
        default: return nil
        }
    }
}
